"""Schemas and output fields for the MLlib scoring stage."""

from pyspark.sql.types import BooleanType
from pyspark.sql.types import DoubleType
from pyspark.sql.types import IntegerType
from pyspark.sql.types import LongType
from pyspark.sql.types import StringType
from pyspark.sql.types import StructField
from pyspark.sql.types import StructType


PROCESSED_EVENT_SCHEMA = StructType(
    [
        StructField("processing_component", StringType()),
        StructField("processed_at", StringType()),
        StructField("otel_signal", StringType()),
        StructField("event_dataset", StringType()),
        StructField("ingestion_component", StringType()),
        StructField("source_topic", StringType()),
        StructField("source_partition", IntegerType()),
        StructField("source_offset", LongType()),
        StructField("source_kafka_timestamp", StringType()),
        StructField("raw_event_sha256", StringType()),
        StructField("ci_event", StringType()),
        StructField("ci_stage", StringType()),
        StructField("ci_status", StringType()),
        StructField("pipeline_status", StringType()),
        StructField("is_failure", BooleanType()),
        StructField("failure_category", StringType()),
        StructField("failure_reason", StringType()),
        StructField("failure_detail", StringType()),
        StructField("error_code", StringType()),
        StructField("risk_hint", DoubleType()),
        StructField("service_name", StringType()),
        StructField("service_module", StringType()),
        StructField("build_tool", StringType()),
        StructField("dependency_cache", StringType()),
        StructField("job_name", StringType()),
        StructField("build_number", IntegerType()),
        StructField("source_branch", StringType()),
        StructField("target_environment", StringType()),
        StructField("deployment_strategy", StringType()),
        StructField("random_scenario", IntegerType()),
        StructField("forced_success", BooleanType()),
        StructField("disk_free_pct", IntegerType()),
        StructField("cpu_temp_c", IntegerType()),
        StructField("compile_time_ms", IntegerType()),
        StructField("test_suite", StringType()),
        StructField("test_total", IntegerType()),
        StructField("passed_tests", IntegerType()),
        StructField("failing_tests", IntegerType()),
        StructField("test_duration_ms", IntegerType()),
        StructField("artifact_name", StringType()),
        StructField("artifact_checksum", StringType()),
        StructField("artifact_size_mb", IntegerType()),
        StructField("replicas_ready", IntegerType()),
        StructField("replicas_expected", IntegerType()),
        StructField("rollout_seconds", IntegerType()),
        StructField("severity_text", StringType()),
        StructField("trace_id", StringType()),
        StructField("span_id", StringType()),
        StructField("span_name", StringType()),
        StructField("http_method", StringType()),
        StructField("http_route", StringType()),
        StructField("http_status_code", IntegerType()),
        StructField("exception_type", StringType()),
        StructField("exception_message", StringType()),
        StructField("raw_event", StringType()),
    ]
)

SCORED_EVENT_FIELDS = (
    "processing_component",
    "spark_processing_component",
    "ml_scored_at",
    "ml_model_name",
    "ml_model_version",
    "ml_model_type",
    "ml_risk_score",
    "ml_risk_band",
    "ml_failure_prediction",
    "ml_anomaly_class",
    "ml_model_probability",
    "ml_feature_risk_hint",
    "ml_feature_duration_signal",
    "ml_feature_test_failure_ratio",
    "ml_feature_low_disk_signal",
    "ml_feature_heat_signal",
    "ml_feature_deploy_gap_signal",
    "ml_feature_http_error_signal",
    "ml_feature_cache_miss_signal",
    "ml_source_topic",
    "ml_source_partition",
    "ml_source_offset",
    "ml_source_kafka_timestamp",
    "processed_at",
    "otel_signal",
    "event_dataset",
    "ingestion_component",
    "source_topic",
    "source_partition",
    "source_offset",
    "source_kafka_timestamp",
    "raw_event_sha256",
    "ci_event",
    "ci_stage",
    "ci_status",
    "pipeline_status",
    "is_failure",
    "failure_category",
    "failure_reason",
    "failure_detail",
    "error_code",
    "risk_hint",
    "service_name",
    "service_module",
    "build_tool",
    "dependency_cache",
    "job_name",
    "build_number",
    "source_branch",
    "target_environment",
    "deployment_strategy",
    "random_scenario",
    "forced_success",
    "disk_free_pct",
    "cpu_temp_c",
    "compile_time_ms",
    "test_suite",
    "test_total",
    "passed_tests",
    "failing_tests",
    "test_duration_ms",
    "artifact_name",
    "artifact_checksum",
    "artifact_size_mb",
    "replicas_ready",
    "replicas_expected",
    "rollout_seconds",
    "severity_text",
    "trace_id",
    "span_id",
    "span_name",
    "http_method",
    "http_route",
    "http_status_code",
    "exception_type",
    "exception_message",
    "raw_event",
)
