"""Schemas and output fields for the MLlib scoring stage."""

from pyspark.sql.types import BooleanType
from pyspark.sql.types import DoubleType
from pyspark.sql.types import IntegerType
from pyspark.sql.types import LongType
from pyspark.sql.types import StringType
from pyspark.sql.types import StructField
from pyspark.sql.types import StructType


PROCESSED_EVENT_SCHEMA = StructType(
    [
        StructField("processing_component", StringType()),
        StructField("processed_at", StringType()),
        StructField("otel_signal", StringType()),
        StructField("event_dataset", StringType()),
        StructField("ingestion_component", StringType()),
        StructField("source_topic", StringType()),
        StructField("source_partition", IntegerType()),
        StructField("source_offset", LongType()),
        StructField("source_kafka_timestamp", StringType()),
        StructField("raw_event_sha256", StringType()),
        StructField("observed_at", StringType()),
        StructField("source_system", StringType()),
        StructField("event_source", StringType()),
        StructField("ci_event", StringType()),
        StructField("ci_stage", StringType()),
        StructField("stage_order", IntegerType()),
        StructField("ci_status", StringType()),
        StructField("pipeline_status", StringType()),
        StructField("event_kind", StringType()),
        StructField("signal_domain", StringType()),
        StructField("signal_name", StringType()),
        StructField("signal_value", DoubleType()),
        StructField("signal_unit", StringType()),
        StructField("severity_level", StringType()),
        StructField("event_summary", StringType()),
        StructField("is_failure", BooleanType()),
        StructField("alert_candidate", BooleanType()),
        StructField("alert_type", StringType()),
        StructField("alert_reason", StringType()),
        StructField("failure_category", StringType()),
        StructField("failure_reason", StringType()),
        StructField("failure_detail", StringType()),
        StructField("error_code", StringType()),
        StructField("risk_hint", DoubleType()),
        StructField("service_name", StringType()),
        StructField("service_module", StringType()),
        StructField("build_tool", StringType()),
        StructField("dependency_cache", StringType()),
        StructField("job_name", StringType()),
        StructField("build_number", IntegerType()),
        StructField("source_branch", StringType()),
        StructField("commit_sha", StringType()),
        StructField("target_environment", StringType()),
        StructField("deployment_strategy", StringType()),
        StructField("random_scenario", IntegerType()),
        StructField("forced_success", BooleanType()),
        StructField("scm_latency_ms", IntegerType()),
        StructField("retry_count", IntegerType()),
        StructField("disk_free_pct", IntegerType()),
        StructField("cpu_temp_c", IntegerType()),
        StructField("compile_time_ms", IntegerType()),
        StructField("test_suite", StringType()),
        StructField("test_total", IntegerType()),
        StructField("passed_tests", IntegerType()),
        StructField("failing_tests", IntegerType()),
        StructField("test_duration_ms", IntegerType()),
        StructField("artifact_name", StringType()),
        StructField("artifact_checksum", StringType()),
        StructField("artifact_size_mb", IntegerType()),
        StructField("replicas_ready", IntegerType()),
        StructField("replicas_expected", IntegerType()),
        StructField("rollout_seconds", IntegerType()),
        StructField("trace_id", StringType()),
        StructField("span_id", StringType()),
        StructField("span_name", StringType()),
        StructField("feature_scm_pressure", DoubleType()),
        StructField("feature_agent_pressure", DoubleType()),
        StructField("feature_build_pressure", DoubleType()),
        StructField("feature_test_pressure", DoubleType()),
        StructField("feature_artifact_pressure", DoubleType()),
        StructField("feature_deploy_pressure", DoubleType()),
        StructField("feature_overall_pressure", DoubleType()),
    ]
)

SCORED_EVENT_FIELDS = (
    "processing_component",
    "ml_scored_at",
    "ml_model_name",
    "ml_model_version",
    "ml_model_type",
    "ml_prediction_target",
    "ml_stage_failure_warning",
    "predicted_failure_stage",
    "warning_level",
    "warning_type",
    "warning_title",
    "warning_message",
    "warning_reason",
    "recommended_action",
    "dashboard_category",
    "raw_event_sha256",
    "observed_at",
    "job_name",
    "build_number",
    "service_name",
    "ci_stage",
    "stage_order",
    "ci_status",
    "pipeline_status",
    "event_kind",
    "signal_domain",
    "signal_name",
    "signal_value",
    "signal_unit",
    "severity_level",
    "event_summary",
    "is_failure",
    "alert_candidate",
    "failure_category",
    "failure_reason",
    "target_environment",
)
